import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/common/header/component/Header';
import { NextIntlClientProvider } from 'next-intl';
import { LayoutClientWrapper } from '@/common/env/wrapper/LayoutClientWrapper';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <NextIntlClientProvider>
                    <LayoutClientWrapper>
                        <Header />
                        <main>{children}</main>
                    </LayoutClientWrapper>
                </NextIntlClientProvider>
                <div id="portal" />
            </body>
        </html>
    );
}
